Refactorio/RedMew

- locale/gen_shared/perlin_noise.lua
- Optimise the gradient function
- Perform a bitwise AND operation instead of a modulo
- Comment code more clearly
- Store all the functions in the perlin table
> Improve Perlin noise implementation

- custom_commands.lua
- locale/gen_ores/glitter_ores.lua
- map_layout.lua
Randomizes the ore patches outside of spawn area to density settings
> Glitter Ores Map Generation

- locale/gen_ores/glitter_ores.lua
- locale/gen_terrain/tris_chunk_grid.lua
- map_layout.lua
Also added game play comments to the glitter ore for future reference
> Added chunk grid terrain generation

- tasklist.lua
Changed to a local repo branch, confirming all git is correct, minor update to the tasklist
> Update to the icon per Red and popular input

- control.lua
- custom_commands.lua
- map_layout.lua
- nuke_control.lua
- tasklist.lua
> Dev forcetoggle qol fixes

- locale/gen_combined/island_resort.lua
Overall -- did not affect game stutter, however code is playtested.
> Cleanup to island resort code, elseifs and whitespace mostly.

- locale/utils/utils.lua
- nuke_control.lua
> Dev custom prints

- fish_market.lua
- nuke_control.lua
> Artillery control

- control.lua
- server_api.lua
- user_groups.lua
added to control.lua : require "server_api"
added new file "server_api.lua"
> Changes to Control.lua, New file (server-api.lua)

- server_api.lua
updated bot_command_time() code to tell seconds, minutes, hours and days.
> /time improved

- custom_commands.lua
- nuke_control.lua
- user_groups.lua
- utils/utils.lua
- Fixed bugs in user_groups
- Moved get_actor into utils/utils.lua
> Added missing require user_groups into nuke_control.lua

- control.lua
> Add plague's colors

- custom_commands.lua
- utils/utils.lua
> Implemented /a and /report

- custom_commands.lua
Because I might have been the first to do it, but I would also like to be the last.
Supercedes and closes https://github.com/Valansch/RedMew/pull/197
> Add a check before granting all techs to player force

- map_gen/Diggy/Config.lua
- map_gen/Diggy/Debug.lua
- map_gen/Diggy/Feature/DiggyCaveCollapse.lua
- map_gen/Diggy/Feature/SetupPlayer.lua
Can probably need more testing but it seemed to work fine.
It can also be optimized because the conversion happends at a very low level. But i had trouble that so this is a working solution for now.
> Changed stress map resolution

- map_gen/Biter_Battles/biter_battles.lua
- map_gen/Biter_Battles/biter_battles_changelog.txt
- map_gen/Biter_Battles/biter_battles_terrain.lua
- map_gen/Biter_Battles/biter_battles_terrain_neko.lua
- map_gen/Biter_Battles/config.lua
- map_gen/Biter_Battles/control.lua
- map_gen/Biter_Battles/corpse_util.lua
- map_gen/Biter_Battles/map_gen/shared/simplex_noise.lua
- map_gen/Biter_Battles/utils/PriorityQueue.lua
- map_gen/Biter_Battles/utils/Queue.lua
- map_gen/Biter_Battles/utils/Task.lua
- map_gen/Biter_Battles/utils/event.lua
- map_gen/Biter_Battles/utils/global.lua
- map_gen/Biter_Battles/utils/global_token.lua
- map_gen/Biter_Battles/utils/gui.lua
- map_gen/Biter_Battles/utils/list_utils.lua
- map_gen/Biter_Battles/utils/utils.lua
Credit to @M3wM3w for the code.
This PR the first step toward integrating the scenario: getting the files themselves into the codebase so that it can be worked on collaboratively and begin a commit history.
> Initial merge of biter battles by mewmew

- map_gen/misc/car_body.lua
- map_layout.lua
Just a dumb thought I had, no idea if it'll ever be used. :smile:
> Add the ability to lock players into cars

- README.md
Who needs documentation right? I just want to play this awesome redmew map!
This small change should hopefully guide players in the right direction to look for a self hosted or single player scenario.
> Made the documentation clear for single player/LAN

- map_gen/Diggy/Scenario.lua
- map_gen/misc/change_landfill_tile.lua
- map_layout.lua
> [diggy] landfill now spanws dirt-[1-7]

- control.lua
- features/free_item_logging.lua
At the same time, we should probably also remove the player-specific code since we can still track cheating.
Thoughts @grilledham @Valansch ?
> Move cheat tracking outside of control.lua

- control.lua
A last restructuring of control.lua after the recent changes
> Reorganize control

- custom_commands.lua
- report.lua
**Jail button**
I tried to add a jail button to the 'showreports' gui.
I can't speak for the quality of the code.
I moved major parts of the jail_player(cmd) in custom_commands.lua to report.lua. Added a new button, downsized it and added an on_click event that calls report.jail(player, target)
I also added a notification sound for admins when a new report is made. (Or rather when the showreport windows is opened by a new report)
Feel free to improve it.
**What I haven't figured out:**
~~The strings "You have been placed in jail [...]" it prints out to the target seems to have an indentation.~~
~~^ also happens for the 'removed weapon' string~~
If it really works with multiple reports and different people.
Closes #215
> Jail button in 'showreports'

- map_gen/Diggy/Config.lua
- map_gen/Diggy/Feature/ScatteredResources.lua
issue #309 
continuation of #327 because of my horrible git skills
> ore weights instead of chances

- map_gen/presets/maltease_crossings.lua
Re-scope variables, remove whitespaces, remove unused arguments
> Maltese crossings fixes

- features/report.lua
Resolves https://github.com/Valansch/RedMew/issues/325
> Remove local ref for submit button

- .gitignore
- map_gen/Diggy/Feature/NightTime.lua
Not much else to say. Title speaks for itself
> Added Luadoc for NightTime.lua

- control.lua
- features/gui/info.lua
Removed old welcome message and replaced it with a short reminder on how to change keybinding to enable chat.
Leaving it here to see what people think
#282 discusses the problems of people asking questions available in the info.gui. This is a suggestion on how to help people notice this gui.
> Made info.gui display on player_created

- map_gen/presets/diagonal_ribbon.lua
I don't know if this is something we want to start doing overall. I know that when I look at map presets it would be nice to know what settings worked and didn't work.
> Diagonal_ribbon postmortum

- features/player_create.lua
- features/user_groups.lua
Fixes #333 overwriting https://github.com/Valansch/RedMew/pull/340
> Create player fix

- map_gen/Diggy/Feature/MarketExchange.lua
Fixed the market not progressing unto level 4, until level 11.
> Diggy - Gamebreaking fix

- map_gen/Diggy/Config.lua
- map_gen/Diggy/Feature/DiggyHole.lua
- map_gen/Diggy/Feature/SimpleRoomGenerator.lua
Huge rocks spawn on top of ore tendrils (from BlueTemplar)
> changes, courtesy of BlueTemplar

- map_gen/Diggy/Feature/MarketExchange.lua
> Changed the level up chat messages for diggy 
